DROP TABLE IF EXISTS TRACK;
DROP TABLE IF EXISTS ALBUM;
DROP TABLE IF EXISTS ARTISTA;
DROP TABLE IF EXISTS GENERO_MUSICAL;
DROP TABLE IF EXISTS EMPRESA_DISCOGRAFICA;
CREATE TABLE ARTISTA(
    ID_ARTISTA INT AUTO_INCREMENT,
    NOMBRE_ARTISTA VARCHAR(100),
    NACIONALIDAD VARCHAR(100),
    PRIMARY KEY(ID_ARTISTA)
)ENGINE=INNODB;

INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('ENANITOS VERDES','ARGENTINA');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('SODA STEREO','ARGENTINA');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('LIBIDO','PERU');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('LUIS MIGUEL','MEXICO');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('PEDRO SUAREZ VERTIZ','PERU');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('AMEN','PERU');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('MAR DE COPAS','PERU');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('DANIEL F','PERU');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('MARC ANTHONY','PUERTO RICO');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('BELINDA','MEXICO');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('CRISTIAN CASTRO','MEXICO');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('GIANMARCO','PERU');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('CARLOS VIVES','COLOMBIA');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('SHAKIRA','COLOMBIA');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('MAROON 5','ESTADOS UNIDOS');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('GREEN DAY','ESTADOS UNIDOS');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('ARCTIC MONKEYS','REINO UNIDO');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('MOLOTOV','MEXICO');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('REIK','MEXICO');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('GORILLAZ','REINO UNIDO');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('ARIANA GRANDE','ESTADOS UNIDOS');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('BRITNEY SPEARS','ESTADOS UNIDOS');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('ANITTA','BRASIL');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('ENRIQUE IGLESIAS','ESPAÑA');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('JENNIFER LOPEZ','ESTADOS UNIDOS');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('MANÁ','MEXICO');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('ADELE','REINO UNIDO');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('MY CHEMICAL ROMANCE','ESTADOS UNIDOS');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('PANIC AT THE DISCO','ESTADOS UNIDOS');
INSERT INTO ARTISTA(NOMBRE_ARTISTA, NACIONALIDAD) VALUES('EVANESCENCE','ESTADOS UNIDOS');

CREATE TABLE GENERO_MUSICAL(
	ID_GENERO_MUSICAL INT AUTO_INCREMENT,
    NOMBRE_GENERO VARCHAR(100),
    PRIMARY KEY(ID_GENERO_MUSICAL)
)ENGINE=INNODB;

INSERT INTO GENERO_MUSICAL(NOMBRE_GENERO) VALUES('ROCK');
INSERT INTO GENERO_MUSICAL(NOMBRE_GENERO) VALUES('POP');
INSERT INTO GENERO_MUSICAL(NOMBRE_GENERO) VALUES('REGGAE');
INSERT INTO GENERO_MUSICAL(NOMBRE_GENERO) VALUES('REGGAETON');
INSERT INTO GENERO_MUSICAL(NOMBRE_GENERO) VALUES('TECHNO');
INSERT INTO GENERO_MUSICAL(NOMBRE_GENERO) VALUES('SALSA');
INSERT INTO GENERO_MUSICAL(NOMBRE_GENERO) VALUES('METAL');
INSERT INTO GENERO_MUSICAL(NOMBRE_GENERO) VALUES('BALADA');
INSERT INTO GENERO_MUSICAL(NOMBRE_GENERO) VALUES('BOLERO');
INSERT INTO GENERO_MUSICAL(NOMBRE_GENERO) VALUES('CUMBIA');
INSERT INTO GENERO_MUSICAL(NOMBRE_GENERO) VALUES('INDIE');
INSERT INTO GENERO_MUSICAL(NOMBRE_GENERO) VALUES('RAP');
INSERT INTO GENERO_MUSICAL(NOMBRE_GENERO) VALUES('HIP HOP');
INSERT INTO GENERO_MUSICAL(NOMBRE_GENERO) VALUES('ELETRÓNICA');
INSERT INTO GENERO_MUSICAL(NOMBRE_GENERO) VALUES('KPOP');

CREATE TABLE EMPRESA_DISCOGRAFICA(
	ID_EMPRESA_DISCOGRAFICA INT AUTO_INCREMENT,
    NOMBRE_EMPRESA VARCHAR(100),
    PRIMARY KEY(ID_EMPRESA_DISCOGRAFICA)
)ENGINE=INNODB;

INSERT INTO EMPRESA_DISCOGRAFICA(NOMBRE_EMPRESA) VALUES('WARNER MUSIC INC');
INSERT INTO EMPRESA_DISCOGRAFICA(NOMBRE_EMPRESA) VALUES('COLUMBIA RECORDS');
INSERT INTO EMPRESA_DISCOGRAFICA(NOMBRE_EMPRESA) VALUES('SONY MASTERWORKS');
INSERT INTO EMPRESA_DISCOGRAFICA(NOMBRE_EMPRESA) VALUES('SONY RECORDS INC');
INSERT INTO EMPRESA_DISCOGRAFICA(NOMBRE_EMPRESA) VALUES('SONY MUSIC ENTERTAINMENT');
INSERT INTO EMPRESA_DISCOGRAFICA(NOMBRE_EMPRESA) VALUES('LEGACY RECORDS');
INSERT INTO EMPRESA_DISCOGRAFICA(NOMBRE_EMPRESA) VALUES('WALT DISNEY MUSIC');
INSERT INTO EMPRESA_DISCOGRAFICA(NOMBRE_EMPRESA) VALUES('UNIVERSAL MUSIC GROUP');
INSERT INTO EMPRESA_DISCOGRAFICA(NOMBRE_EMPRESA) VALUES('BMG MUSIC');

CREATE TABLE ALBUM(
	ID_ALBUM INT AUTO_INCREMENT,
    FID_GENERO_MUSICAL INT,
    FID_EMPRESA_DISCOGRAFICA INT,
    FID_ARTISTA INT,
    NOMBRE_ALBUM VARCHAR(100),
    FECHA_LANZAMIENTO DATE,
    PORTADA LONGBLOB,
    DESCRIPCION VARCHAR(1000),
    PRIMARY KEY(ID_ALBUM),
    FOREIGN KEY(FID_GENERO_MUSICAL) REFERENCES GENERO_MUSICAL(ID_GENERO_MUSICAL),
    FOREIGN KEY(FID_EMPRESA_DISCOGRAFICA) REFERENCES EMPRESA_DISCOGRAFICA(ID_EMPRESA_DISCOGRAFICA),
    FOREIGN KEY(FID_ARTISTA) REFERENCES ARTISTA(ID_ARTISTA)
)ENGINE=INNODB;

CREATE TABLE TRACK(
	ID_TRACK INT AUTO_INCREMENT,
    FID_ALBUM INT,
    POSICION_TRACK INT,
    NOMBRE_TRACK VARCHAR(100),
    DURACION_TRACK TIME,
    PRIMARY KEY(ID_TRACK),
    FOREIGN KEY(FID_ALBUM) REFERENCES ALBUM(ID_ALBUM)
)ENGINE=INNODB;

DELIMITER $
DROP PROCEDURE IF EXISTS LISTAR_ARTISTAS$
CREATE PROCEDURE LISTAR_ARTISTAS(
	IN _NOMBRE_ARTISTA VARCHAR(100)
)
BEGIN
	SELECT ID_ARTISTA, NOMBRE_ARTISTA, NACIONALIDAD FROM ARTISTA WHERE NOMBRE_ARTISTA LIKE CONCAT('%',_NOMBRE_ARTISTA,'%') ORDER BY NOMBRE_ARTISTA;
END$

DROP PROCEDURE IF EXISTS LISTAR_GENEROS_MUSICALES$
CREATE PROCEDURE LISTAR_GENEROS_MUSICALES()
BEGIN
	SELECT ID_GENERO_MUSICAL, NOMBRE_GENERO FROM GENERO_MUSICAL ORDER BY NOMBRE_GENERO;
END$

DROP PROCEDURE IF EXISTS LISTAR_EMPRESAS_DISCOGRAFICAS$
CREATE PROCEDURE LISTAR_EMPRESAS_DISCOGRAFICAS(
	IN _NOMBRE_EMPRESA VARCHAR(100)
)
BEGIN
	SELECT ID_EMPRESA_DISCOGRAFICA, NOMBRE_EMPRESA FROM EMPRESA_DISCOGRAFICA WHERE NOMBRE_EMPRESA LIKE CONCAT('%',_NOMBRE_EMPRESA,'%') ORDER BY NOMBRE_EMPRESA;
END$

DROP PROCEDURE IF EXISTS INSERTAR_ALBUM$
CREATE PROCEDURE INSERTAR_ALBUM(
	OUT _ID_ALBUM INT,
    IN _FID_GENERO_MUSICAL INT,
    IN _FID_EMPRESA_DISCOGRAFICA INT,
    IN _FID_ARTISTA INT,
    IN _NOMBRE_ALBUM VARCHAR(100),
    IN _FECHA_LANZAMIENTO DATETIME,
    IN _PORTADA LONGBLOB,
    IN _DESCRIPCION VARCHAR(1000)
)
BEGIN
	INSERT INTO ALBUM(FID_GENERO_MUSICAL,FID_EMPRESA_DISCOGRAFICA,FID_ARTISTA,NOMBRE_ALBUM,FECHA_LANZAMIENTO,PORTADA,DESCRIPCION) 
    VALUES(_FID_GENERO_MUSICAL,_FID_EMPRESA_DISCOGRAFICA,_FID_ARTISTA,_NOMBRE_ALBUM,_FECHA_LANZAMIENTO,_PORTADA,_DESCRIPCION);
    SET _ID_ALBUM = last_insert_id();
END$

DROP PROCEDURE IF EXISTS LISTAR_ALBUMES$
CREATE PROCEDURE LISTAR_ALBUMES(
	IN _NOMBRE_ALBUM VARCHAR(100)
)
BEGIN
	SELECT AB.ID_ALBUM, AB.NOMBRE_ALBUM, AB.FECHA_LANZAMIENTO, AB.PORTADA, AB.DESCRIPCION,
    AR.ID_ARTISTA, AR.NACIONALIDAD, AR.NOMBRE_ARTISTA, 
    GM.ID_GENERO_MUSICAL, GM.NOMBRE_GENERO,
    ED.ID_EMPRESA_DISCOGRAFICA, ED.NOMBRE_EMPRESA
    FROM ALBUM AB INNER JOIN ARTISTA AR ON AR.ID_ARTISTA = AB.FID_ARTISTA 
    INNER JOIN GENERO_MUSICAL GM ON GM.ID_GENERO_MUSICAL = AB.FID_GENERO_MUSICAL 
    INNER JOIN EMPRESA_DISCOGRAFICA ED ON ED.ID_EMPRESA_DISCOGRAFICA = AB.FID_EMPRESA_DISCOGRAFICA 
    WHERE (AB.NOMBRE_ALBUM LIKE CONCAT('%',_NOMBRE_ALBUM,'%')) OR (AR.NOMBRE_ARTISTA LIKE CONCAT('%',_NOMBRE_ALBUM,'%')) ORDER BY AB.ID_ALBUM;
END$

DROP PROCEDURE IF EXISTS LISTAR_TRACKS_POR_ID_ALBUM$
CREATE PROCEDURE LISTAR_TRACKS_POR_ID_ALBUM(
	IN _ID_ALBUM INT
)
BEGIN
	SELECT ID_TRACK, POSICION_TRACK, NOMBRE_TRACK, DURACION_TRACK FROM TRACK WHERE FID_ALBUM = _ID_ALBUM ORDER BY POSICION_TRACK;
END$

DROP PROCEDURE IF EXISTS INSERTAR_TRACK$
CREATE PROCEDURE INSERTAR_TRACK(
	IN _FID_ALBUM INT,
    IN _POSICION_TRACK INT,
    IN _NOMBRE_TRACK VARCHAR(100),
    IN _DURACION_TRACK VARCHAR(100)
)
BEGIN
	INSERT INTO TRACK(FID_ALBUM, POSICION_TRACK, NOMBRE_TRACK, DURACION_TRACK) 
    VALUES(_FID_ALBUM, _POSICION_TRACK, _NOMBRE_TRACK, _DURACION_TRACK);
END$