DROP TABLE IF EXISTS LINEA_DETALLE_PROMOCION;
DROP TABLE IF EXISTS PROMOCION;
DROP TABLE IF EXISTS PRODUCTO_PRESENTACION;
DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS PRESENTACION;
DROP TABLE IF EXISTS LINEA_ORDEN_VENTA;
DROP TABLE IF EXISTS ORDEN_VENTA;
DROP TABLE IF EXISTS ITEM_VENTA;
DROP TABLE IF EXISTS TIPO_ITEM;
DROP TABLE IF EXISTS CLIENTE;
CREATE TABLE CLIENTE(
	ID_CLIENTE INT AUTO_INCREMENT,
    DNI VARCHAR(8) UNIQUE,
    NOMBRE_COMPLETO VARCHAR(100),
    PRIMARY KEY(ID_CLIENTE)
)ENGINE=INNODB;
CREATE TABLE ORDEN_VENTA(
	ID_ORDEN_VENTA INT AUTO_INCREMENT,
    FID_CLIENTE INT,
    FECHA_VENTA DATE,
	TOTAL DECIMAL(10,2),
    PRIMARY KEY(ID_ORDEN_VENTA),
    FOREIGN KEY(FID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
)ENGINE=INNODB;
CREATE TABLE TIPO_ITEM(
	ID_TIPO_ITEM INT AUTO_INCREMENT,
    TIPO VARCHAR(50),
    PRIMARY KEY(ID_TIPO_ITEM)
)ENGINE=INNODB;
CREATE TABLE ITEM_VENTA(
	ID_ITEM_VENTA INT AUTO_INCREMENT,
    FID_TIPO_ITEM INT,
	PRECIO_UNITARIO DECIMAL(10,2),
    FOREIGN KEY(FID_TIPO_ITEM) REFERENCES TIPO_ITEM(ID_TIPO_ITEM),
    PRIMARY KEY(ID_ITEM_VENTA)
)ENGINE=INNODB;
CREATE TABLE LINEA_ORDEN_VENTA(
	ID_LINEA_ORDEN_VENTA INT AUTO_INCREMENT,
    FID_ORDEN_VENTA INT,
    FID_ITEM_VENTA INT,
    CANTIDAD INT,
    SUBTOTAL DECIMAL(10,2),
    FOREIGN KEY(FID_ORDEN_VENTA) REFERENCES ORDEN_VENTA(ID_ORDEN_VENTA),
    FOREIGN KEY(FID_ITEM_VENTA) REFERENCES ITEM_VENTA(ID_ITEM_VENTA),
    PRIMARY KEY(ID_LINEA_ORDEN_VENTA)
)ENGINE=INNODB;
CREATE TABLE PRODUCTO(
	ID_PRODUCTO INT AUTO_INCREMENT,
    NOMBRE_PRODUCTO VARCHAR(100),
    PRIMARY KEY(ID_PRODUCTO)
)ENGINE=INNODB;
CREATE TABLE PRESENTACION(
	ID_PRESENTACION INT AUTO_INCREMENT,
    UNIDAD_MEDIDA VARCHAR(100),
    PRIMARY KEY(ID_PRESENTACION)
)ENGINE=INNODB;
CREATE TABLE PRODUCTO_PRESENTACION(
	ID_PRODUCTO_PRESENTACION INT AUTO_INCREMENT,
    FID_PRODUCTO INT,
    FID_PRESENTACION INT,
    PRIMARY KEY(ID_PRODUCTO_PRESENTACION),
    FOREIGN KEY(FID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
    FOREIGN KEY(FID_PRESENTACION) REFERENCES PRESENTACION(ID_PRESENTACION),
    FOREIGN KEY(ID_PRODUCTO_PRESENTACION) REFERENCES ITEM_VENTA(ID_ITEM_VENTA),
    UNIQUE (FID_PRODUCTO, FID_PRESENTACION)
)ENGINE=INNODB;
CREATE TABLE PROMOCION(
	ID_PROMOCION INT AUTO_INCREMENT,
    NOMBRE_PROMOCION VARCHAR(70),
	ACTIVO TINYINT,
    PRIMARY KEY(ID_PROMOCION),
    FOREIGN KEY(ID_PROMOCION) REFERENCES ITEM_VENTA(ID_ITEM_VENTA)
)ENGINE=INNODB;
CREATE TABLE LINEA_DETALLE_PROMOCION(
	ID_LINEA_DETALLE_PROMOCION INT AUTO_INCREMENT,
    FID_PROMOCION INT,
    FID_PRODUCTO_PRESENTACION INT,
    CANTIDAD INT,
	ACTIVO TINYINT,
    PRIMARY KEY(ID_LINEA_DETALLE_PROMOCION),
    FOREIGN KEY(FID_PROMOCION) REFERENCES PROMOCION(ID_PROMOCION),
    FOREIGN KEY(FID_PRODUCTO_PRESENTACION) REFERENCES PRODUCTO_PRESENTACION(ID_PRODUCTO_PRESENTACION)
)ENGINE=INNODB;
DELIMITER $
DROP PROCEDURE IF EXISTS INSERTAR_CLIENTE$
CREATE PROCEDURE INSERTAR_CLIENTE(
	_DNI VARCHAR(8),
    _NOMBRE_COMPLETO VARCHAR(100)
)
BEGIN
	INSERT INTO CLIENTE(DNI,NOMBRE_COMPLETO) VALUES(_DNI,_NOMBRE_COMPLETO);
END$
CALL INSERTAR_CLIENTE('18189534','RAMIRO ALBERTO ABANTO APAESTEGUI')$
CALL INSERTAR_CLIENTE('10429954','ISABEL ABANTO ROJAS')$
CALL INSERTAR_CLIENTE('40347647','ROSA KARINA ABARCA GONZALES')$
CALL INSERTAR_CLIENTE('40443072','YULIANA DEL ROSARIO ABARCA SALAZAR')$
CALL INSERTAR_CLIENTE('28224852','CIRILO ABREGU ROBLES')$
CALL INSERTAR_CLIENTE('40051851','DENNIS LISBETH ABURTO JARA')$
CALL INSERTAR_CLIENTE('40193669','PASCUAL DAVID ACCILIO LEANDRO')$
CALL INSERTAR_CLIENTE('41823093','DIANA PAOLA ACEVEDO VARGAS')$
CALL INSERTAR_CLIENTE('42830931','JAVIER ACHING ACOSTA')$
CALL INSERTAR_CLIENTE('08864242','ZOILO ALEJANDRO ACOSTA BOADA')$
CALL INSERTAR_CLIENTE('06811781','ABRAHAM FABIAN ACOSTA GONZALES')$
CALL INSERTAR_CLIENTE('32989137','TEODORA BEATRIZ ACOSTA SALVADOR')$
CALL INSERTAR_CLIENTE('25787785','GLADYS PAOLA ACUÑA MAYTA')$
CALL INSERTAR_CLIENTE('23938444','ANTONIETA NORMA ACURIO RIVAS')$
CALL INSERTAR_CLIENTE('02817490','RICARDO WILMER ADANAQUE ROSAS')$
CALL INSERTAR_CLIENTE('20070663','ROMELIO FORTUNATO ADRIANO CAMPOSANO')$
CALL INSERTAR_CLIENTE('16522452','JUAN ADRIANZEN FERNANDEZ')$
CALL INSERTAR_CLIENTE('41215234','GABRIELA ADRIANZEN SALDARRIAGA')$
CALL INSERTAR_CLIENTE('41708337','CYNTHIA RINA ADVINCULA REINOSO')$
CALL INSERTAR_CLIENTE('41419536','JESUS ANTONIO AGAMA CASTAÑEDA')$
CALL INSERTAR_CLIENTE('43911858','JORGE JONATHAN AGAPITO ESPICHAN')$
INSERT INTO TIPO_ITEM(ID_TIPO_ITEM, TIPO) VALUES(1,'PRODUCTO_PRESENTACION')$
INSERT INTO TIPO_ITEM(ID_TIPO_ITEM, TIPO) VALUES(2,'PROMOCION')$
DROP PROCEDURE IF EXISTS INSERTAR_PRODUCTO_PRESENTACION$
CREATE PROCEDURE INSERTAR_PRODUCTO_PRESENTACION(
	OUT _ID_ITEM_VENTA INT,
    IN _PRECIO_UNITARIO DECIMAL(10,2),
    IN _FID_PRODUCTO INT,
    IN _FID_PRESENTACION INT
)
BEGIN
	INSERT INTO ITEM_VENTA(FID_TIPO_ITEM, PRECIO_UNITARIO) VALUES (1, _PRECIO_UNITARIO);
    SET _ID_ITEM_VENTA = last_insert_id();
    INSERT INTO PRODUCTO_PRESENTACION(ID_PRODUCTO_PRESENTACION, FID_PRODUCTO, FID_PRESENTACION) VALUES(_ID_ITEM_VENTA, _FID_PRODUCTO, _FID_PRESENTACION);
END$
DROP PROCEDURE IF EXISTS INSERTAR_PROMOCION$
CREATE PROCEDURE INSERTAR_PROMOCION(
	OUT _ID_ITEM_VENTA INT,
    IN _PRECIO_UNITARIO DECIMAL(10,2),
    IN _NOMBRE_PROMOCION VARCHAR(70)
)
BEGIN
	INSERT INTO ITEM_VENTA(FID_TIPO_ITEM, PRECIO_UNITARIO) VALUES (2, _PRECIO_UNITARIO);
    SET _ID_ITEM_VENTA = last_insert_id();
    INSERT INTO PROMOCION(ID_PROMOCION, NOMBRE_PROMOCION, ACTIVO) VALUES(_ID_ITEM_VENTA, _NOMBRE_PROMOCION, 1);
END$
DROP PROCEDURE IF EXISTS INSERTAR_LINEA_DETALLE_PROMOCION$
CREATE PROCEDURE INSERTAR_LINEA_DETALLE_PROMOCION(
	_FID_PROMOCION INT,
    _FID_PRODUCTO_PRESENTACION INT,
    _CANTIDAD INT
)
BEGIN
	INSERT INTO LINEA_DETALLE_PROMOCION(FID_PROMOCION, FID_PRODUCTO_PRESENTACION, CANTIDAD, ACTIVO) 
    VALUES(_FID_PROMOCION,_FID_PRODUCTO_PRESENTACION,_CANTIDAD, 1);
END$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(1, '2.25 lts')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(2, '450 ml')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(3, '3 lts')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(4, '400 ml')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(5, '355 ml')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(6, '5 kg')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(7, '750 g')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(8, '2 kg')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(9, '36 g')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(10, '400 g')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(11, '200 g')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(12, '1 kg')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(13, '750 ml')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(14, '500 g')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(15, '680 g')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(16, '950 g')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(17, '220 g')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(18, '250 g')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(19, '75 ml')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(20, '180 ml')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(21, '90 g')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(22, '900 g')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(23, '480 g')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(24, '100 g')$
INSERT INTO PRESENTACION(ID_PRESENTACION, UNIDAD_MEDIDA) VALUES(25, '500 ml')$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(1, 'GASEOSA COCA COLA BOTELLA')$
INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(2, 'GASEOSA FANTA BOTELLA')$
INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(3, 'GASEOSA SPRITE BOTELLA')$
INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(4, 'GASEOSA SPRITE LATA')$
INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(5, 'ARROZ EXTRA COSTEÑO BOLSA')$
INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(6, 'AZUCAR RUBIA DULFINA BOLSA')$
INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(7, 'GALLETAS OREO NABISCO ORIGINAL')$



CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,8.90,1,1)$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,2.49,1,2)$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,5.90,2,3)$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,1.99,3,4)$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,3.90,4,5)$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,16.99,5,6)$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,5.65,6,8)$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,0.70,7,9)$

CALL INSERTAR_PROMOCION(@ID,2.99,'SIX PACK GALLETAS OREO NABISCO ORIGINAL')$
CALL INSERTAR_LINEA_DETALLE_PROMOCION(9,8,6)$


INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(8, 'LECHE EVAPORADA GLORIA LATA')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,3.80,8,10)$

CALL INSERTAR_PROMOCION(@ID,19.20,'SIX PACK LECHE EVAPORADA GLORIA')$
CALL INSERTAR_LINEA_DETALLE_PROMOCION(11,10,6)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(9, 'MANTEQUILLA LAIVE CON SAL BARRA')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,7.99,9,11)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(10, 'MERMELADA GLORIA FRESA BARRIL')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,10.40,10,12)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(11, 'MANJARBLANCO BAZO VELARDE SABOR CASERO')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,3.10,11,11)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(12, 'VINO BLANCO INTIPALKA SAUVIGNON BLANC')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,24.90,12,13)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(13, 'LENTEJAS PAISANA BOLSA')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,5.55,13,14)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(14, 'KETCHUP HUNT''S SQUEEZ')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,13.45,14,15)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(15, 'MAYONESA ALACENA C/TAPA')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,11.50,15,16)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(16, 'MOSTAZA ALACENA')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,3.30,16,17)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(17, 'CAFÉ MOLIDO ALTOMAYO GOURMET BOLSA')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,13.49,17,18)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(18, 'CREMA DENTAL TRIPLE ACCION COLGATE CONTENIDO')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,5.70,18,19)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(19, 'PAN DE MOLDE BIMBO BLANCO BOLSA')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,10.90,19,7)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(20, 'SHAMPOO HEAD & SHOULDERS MANZANA FRESH FRASCO')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,12.40,20,20)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(21, 'ALMENDRA SALADA VALLE ALTO BOLSA')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,11.80,21,21)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(22, 'YOGURT FRUTADO CON FRESA BOTELLA')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,9.90,22,22)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(23, 'CEREAL TRIX CAJA')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,18.80,23,23)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(24, 'PUDÍN DE VAINILLA UNIVERSAL SOBRE')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,2.39,24,24)$

INSERT INTO PRODUCTO(ID_PRODUCTO, NOMBRE_PRODUCTO) VALUES(25, 'SILLAO AJI-NO-SILLAO BOTELLA')$
CALL INSERTAR_PRODUCTO_PRESENTACION(@ID,4.10,25,25)$

CALL INSERTAR_PROMOCION(@ID,24.99,'PACK DESAYUNO RAPID MARKET')$
CALL INSERTAR_LINEA_DETALLE_PROMOCION(29,22,1)$
CALL INSERTAR_LINEA_DETALLE_PROMOCION(29,13,1)$
CALL INSERTAR_LINEA_DETALLE_PROMOCION(29,12,1)$

CALL INSERTAR_PROMOCION(@ID,27.99,'PACK DE LA SEMANA RAPID MARKET')$
CALL INSERTAR_LINEA_DETALLE_PROMOCION(30,6,1)$
CALL INSERTAR_LINEA_DETALLE_PROMOCION(30,7,1)$
CALL INSERTAR_LINEA_DETALLE_PROMOCION(30,16,1)$
CALL INSERTAR_LINEA_DETALLE_PROMOCION(30,10,1)$

DROP PROCEDURE IF EXISTS LISTAR_PRODUCTOS_PRESENTACION$
CREATE PROCEDURE LISTAR_PRODUCTOS_PRESENTACION(
	IN _NOMBRE_PRODUCTO VARCHAR(100)
)
BEGIN
	SELECT ITEM_VENTA.ID_ITEM_VENTA, PRODUCTO.ID_PRODUCTO, PRESENTACION.ID_PRESENTACION, 
    PRODUCTO.NOMBRE_PRODUCTO, PRESENTACION.UNIDAD_MEDIDA, ITEM_VENTA.PRECIO_UNITARIO 
    FROM ITEM_VENTA INNER JOIN PRODUCTO_PRESENTACION ON
    PRODUCTO_PRESENTACION.ID_PRODUCTO_PRESENTACION = ITEM_VENTA.ID_ITEM_VENTA INNER JOIN
    PRESENTACION ON PRESENTACION.ID_PRESENTACION = PRODUCTO_PRESENTACION.FID_PRESENTACION 
    INNER JOIN PRODUCTO ON PRODUCTO.ID_PRODUCTO = PRODUCTO_PRESENTACION.FID_PRODUCTO 
    WHERE CONCAT(PRODUCTO.NOMBRE_PRODUCTO,' ',PRESENTACION.UNIDAD_MEDIDA) LIKE CONCAT('%',_NOMBRE_PRODUCTO,'%');
END$
DROP PROCEDURE IF EXISTS LISTAR_PROMOCIONES$
CREATE PROCEDURE LISTAR_PROMOCIONES(
	IN _NOMBRE_PROMOCION VARCHAR(100)
)
BEGIN
	SELECT ITEM_VENTA.ID_ITEM_VENTA, PROMOCION.NOMBRE_PROMOCION, 
    ITEM_VENTA.PRECIO_UNITARIO FROM ITEM_VENTA INNER JOIN 
    PROMOCION ON PROMOCION.ID_PROMOCION = ITEM_VENTA.ID_ITEM_VENTA 
    WHERE PROMOCION.NOMBRE_PROMOCION LIKE CONCAT('%',_NOMBRE_PROMOCION,'%') AND PROMOCION.ACTIVO = 1;
END$
DROP PROCEDURE IF EXISTS LISTAR_LINEAS_ORDEN_VENTA_POR_ID_ORDEN_VENTA$
CREATE PROCEDURE LISTAR_LINEAS_ORDEN_VENTA_POR_ID_ORDEN_VENTA(
	IN _ID_ORDEN_VENTA INT
)
BEGIN
	SELECT LINEA_ORDEN_VENTA.FID_ORDEN_VENTA, LINEA_ORDEN_VENTA.FID_ITEM_VENTA, LINEA_ORDEN_VENTA.CANTIDAD, LINEA_ORDEN_VENTA.SUBTOTAL, ITEM_VENTA.PRECIO_UNITARIO, TIPO_ITEM.ID_TIPO_ITEM, TIPO_ITEM.TIPO FROM LINEA_ORDEN_VENTA INNER JOIN 
    ITEM_VENTA ON ITEM_VENTA.ID_ITEM_VENTA = LINEA_ORDEN_VENTA.FID_ITEM_VENTA INNER JOIN TIPO_ITEM ON TIPO_ITEM.ID_TIPO_ITEM = ITEM_VENTA.FID_TIPO_ITEM WHERE LINEA_ORDEN_VENTA.FID_ORDEN_VENTA 
    = _ID_ORDEN_VENTA;
END$
DROP PROCEDURE IF EXISTS LISTAR_LINEAS_DETALLE_PROMOCION$
CREATE PROCEDURE LISTAR_LINEAS_DETALLE_PROMOCION(
	IN _ID_PROMOCION INT
)
BEGIN
	SELECT LINEA_DETALLE_PROMOCION.ID_LINEA_DETALLE_PROMOCION, LINEA_DETALLE_PROMOCION.CANTIDAD, PRODUCTO_PRESENTACION.ID_PRODUCTO_PRESENTACION, PRESENTACION.ID_PRESENTACION, PRESENTACION.UNIDAD_MEDIDA, PRODUCTO.ID_PRODUCTO, PRODUCTO.NOMBRE_PRODUCTO, ITEM_VENTA.PRECIO_UNITARIO FROM LINEA_DETALLE_PROMOCION INNER JOIN PRODUCTO_PRESENTACION ON PRODUCTO_PRESENTACION.ID_PRODUCTO_PRESENTACION = LINEA_DETALLE_PROMOCION.FID_PRODUCTO_PRESENTACION INNER JOIN PRESENTACION ON PRESENTACION.ID_PRESENTACION = PRODUCTO_PRESENTACION.FID_PRESENTACION INNER JOIN PRODUCTO ON PRODUCTO.ID_PRODUCTO = PRODUCTO_PRESENTACION.FID_PRODUCTO INNER JOIN ITEM_VENTA ON ITEM_VENTA.ID_ITEM_VENTA = PRODUCTO_PRESENTACION.ID_PRODUCTO_PRESENTACION WHERE LINEA_DETALLE_PROMOCION.ACTIVO = 1 AND LINEA_DETALLE_PROMOCION.FID_PROMOCION = _ID_PROMOCION;
END$
DROP PROCEDURE IF EXISTS ELIMINAR_PROMOCION$
CREATE PROCEDURE ELIMINAR_PROMOCION(
	IN _ID_PROMOCION INT
)
BEGIN
	UPDATE PROMOCION SET ACTIVO = 0 WHERE ID_PROMOCION = _ID_PROMOCION;
END$
DROP PROCEDURE IF EXISTS ACTUALIZAR_PROMOCION$
CREATE PROCEDURE ACTUALIZAR_PROMOCION(
	IN _ID_PROMOCION INT,
	IN _PRECIO_UNITARIO DECIMAL(10,2),
    IN _NOMBRE_PROMOCION VARCHAR(70)
)
BEGIN
	UPDATE ITEM_VENTA SET PRECIO_UNITARIO = _PRECIO_UNITARIO WHERE ID_ITEM_VENTA = _ID_PROMOCION;
	UPDATE PROMOCION SET NOMBRE_PROMOCION = _NOMBRE_PROMOCION WHERE ID_PROMOCION = _ID_PROMOCION;
	UPDATE LINEA_DETALLE_PROMOCION SET ACTIVO = 0 WHERE FID_PROMOCION = _ID_PROMOCION;
END$
DROP PROCEDURE IF EXISTS LISTAR_ORDENES_VENTA$
CREATE PROCEDURE LISTAR_ORDENES_VENTA(
	IN _NOMBRE_CLIENTE VARCHAR(100)
)
BEGIN
	SELECT ORDEN_VENTA.ID_ORDEN_VENTA, 
    CLIENTE.ID_CLIENTE, CLIENTE.DNI, CLIENTE.NOMBRE_COMPLETO, ORDEN_VENTA.FECHA_VENTA, ORDEN_VENTA.TOTAL 
    FROM ORDEN_VENTA INNER JOIN CLIENTE ON ORDEN_VENTA.FID_CLIENTE = CLIENTE.ID_CLIENTE WHERE 
    CLIENTE.NOMBRE_COMPLETO LIKE CONCAT('%',_NOMBRE_CLIENTE,'%');
END$
DROP PROCEDURE IF EXISTS INSERTAR_ORDEN_VENTA$
CREATE PROCEDURE INSERTAR_ORDEN_VENTA(
	OUT _ID_ORDEN_VENTA INT,
    IN _FID_CLIENTE INT,
    IN _TOTAL DECIMAL(10,2)
)
BEGIN
	INSERT INTO ORDEN_VENTA(FID_CLIENTE,FECHA_VENTA,TOTAL) VALUES(_FID_CLIENTE,CURDATE(),_TOTAL);
    SET _ID_ORDEN_VENTA = last_insert_id();
END$
DROP PROCEDURE IF EXISTS INSERTAR_LINEA_ORDEN_VENTA$
CREATE PROCEDURE INSERTAR_LINEA_ORDEN_VENTA(
	IN _FID_ORDEN_VENTA INT,
    IN _FID_ITEM_VENTA INT,
    IN _CANTIDAD INT,
    IN _SUBTOTAL DECIMAL(10,2)
)
BEGIN
	INSERT INTO LINEA_ORDEN_VENTA(FID_ORDEN_VENTA, FID_ITEM_VENTA, CANTIDAD, SUBTOTAL)
    VALUES(_FID_ORDEN_VENTA, _FID_ITEM_VENTA, _CANTIDAD, _SUBTOTAL);
END$

CALL INSERTAR_ORDEN_VENTA(@ID,19,31.74)$
CALL INSERTAR_LINEA_ORDEN_VENTA(1,3,2,11.80)$
CALL INSERTAR_LINEA_ORDEN_VENTA(1,9,1,2.99)$
CALL INSERTAR_LINEA_ORDEN_VENTA(1,7,3,16.95)$

DROP PROCEDURE IF EXISTS LISTAR_CLIENTES$
CREATE PROCEDURE LISTAR_CLIENTES(
	IN _NOMBREDNI VARCHAR(100)
)
BEGIN
	SELECT ID_CLIENTE, DNI, NOMBRE_COMPLETO FROM CLIENTE WHERE DNI LIKE CONCAT('%',_NOMBREDNI,'%') OR NOMBRE_COMPLETO LIKE CONCAT('%',_NOMBREDNI,'%');
END$
DROP PROCEDURE IF EXISTS LISTAR_PRODUCTO_PRESENTACION_POR_ID_ITEM_VENTA$
CREATE PROCEDURE LISTAR_PRODUCTO_PRESENTACION_POR_ID_ITEM_VENTA(
	IN _ID_ITEM_VENTA INT
)
BEGIN
	SELECT ITEM_VENTA.ID_ITEM_VENTA, PRODUCTO.ID_PRODUCTO, PRODUCTO.NOMBRE_PRODUCTO, PRESENTACION.ID_PRESENTACION, PRESENTACION.UNIDAD_MEDIDA, ITEM_VENTA.PRECIO_UNITARIO FROM ITEM_VENTA 
    INNER JOIN PRODUCTO_PRESENTACION ON PRODUCTO_PRESENTACION.ID_PRODUCTO_PRESENTACION = ITEM_VENTA.ID_ITEM_VENTA 
    INNER JOIN PRODUCTO ON PRODUCTO.ID_PRODUCTO = PRODUCTO_PRESENTACION.FID_PRODUCTO 
    INNER JOIN PRESENTACION ON PRESENTACION.ID_PRESENTACION = PRODUCTO_PRESENTACION.FID_PRESENTACION 
    WHERE ITEM_VENTA.ID_ITEM_VENTA = _ID_ITEM_VENTA;
END$
DROP PROCEDURE IF EXISTS LISTAR_PROMOCION_POR_ID_ITEM_VENTA$
CREATE PROCEDURE LISTAR_PROMOCION_POR_ID_ITEM_VENTA(
	IN _ID_ITEM_VENTA INT
)
BEGIN
	SELECT ITEM_VENTA.ID_ITEM_VENTA, PROMOCION.NOMBRE_PROMOCION, ITEM_VENTA.PRECIO_UNITARIO FROM ITEM_VENTA INNER JOIN PROMOCION ON PROMOCION.ID_PROMOCION = ITEM_VENTA.ID_ITEM_VENTA;
END$