//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteLab07.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/", ConfigurationName="Service.Servicio")]
    public interface Servicio {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.marketsoft.pucp.edu.pe/Servicio/insertarPromocionesRequest", ReplyAction="http://services.marketsoft.pucp.edu.pe/Servicio/insertarPromocionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteLab07.Service.insertarPromocionesResponse insertarPromociones(ClienteLab07.Service.insertarPromocionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.marketsoft.pucp.edu.pe/Servicio/insertarPromocionesRequest", ReplyAction="http://services.marketsoft.pucp.edu.pe/Servicio/insertarPromocionesResponse")]
        System.Threading.Tasks.Task<ClienteLab07.Service.insertarPromocionesResponse> insertarPromocionesAsync(ClienteLab07.Service.insertarPromocionesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.marketsoft.pucp.edu.pe/Servicio/actualizarPromocionesRequest", ReplyAction="http://services.marketsoft.pucp.edu.pe/Servicio/actualizarPromocionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteLab07.Service.actualizarPromocionesResponse actualizarPromociones(ClienteLab07.Service.actualizarPromocionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.marketsoft.pucp.edu.pe/Servicio/actualizarPromocionesRequest", ReplyAction="http://services.marketsoft.pucp.edu.pe/Servicio/actualizarPromocionesResponse")]
        System.Threading.Tasks.Task<ClienteLab07.Service.actualizarPromocionesResponse> actualizarPromocionesAsync(ClienteLab07.Service.actualizarPromocionesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.marketsoft.pucp.edu.pe/Servicio/eliminarPromocionesRequest", ReplyAction="http://services.marketsoft.pucp.edu.pe/Servicio/eliminarPromocionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteLab07.Service.eliminarPromocionesResponse eliminarPromociones(ClienteLab07.Service.eliminarPromocionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.marketsoft.pucp.edu.pe/Servicio/eliminarPromocionesRequest", ReplyAction="http://services.marketsoft.pucp.edu.pe/Servicio/eliminarPromocionesResponse")]
        System.Threading.Tasks.Task<ClienteLab07.Service.eliminarPromocionesResponse> eliminarPromocionesAsync(ClienteLab07.Service.eliminarPromocionesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.marketsoft.pucp.edu.pe/Servicio/listarPromocionesRequest", ReplyAction="http://services.marketsoft.pucp.edu.pe/Servicio/listarPromocionesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteLab07.Service.listarPromocionesResponse listarPromociones(ClienteLab07.Service.listarPromocionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.marketsoft.pucp.edu.pe/Servicio/listarPromocionesRequest", ReplyAction="http://services.marketsoft.pucp.edu.pe/Servicio/listarPromocionesResponse")]
        System.Threading.Tasks.Task<ClienteLab07.Service.listarPromocionesResponse> listarPromocionesAsync(ClienteLab07.Service.listarPromocionesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.marketsoft.pucp.edu.pe/Servicio/listarProductosRequest", ReplyAction="http://services.marketsoft.pucp.edu.pe/Servicio/listarProductosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteLab07.Service.listarProductosResponse listarProductos(ClienteLab07.Service.listarProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.marketsoft.pucp.edu.pe/Servicio/listarProductosRequest", ReplyAction="http://services.marketsoft.pucp.edu.pe/Servicio/listarProductosResponse")]
        System.Threading.Tasks.Task<ClienteLab07.Service.listarProductosResponse> listarProductosAsync(ClienteLab07.Service.listarProductosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.marketsoft.pucp.edu.pe/Servicio/helloRequest", ReplyAction="http://services.marketsoft.pucp.edu.pe/Servicio/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(itemVenta))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteLab07.Service.helloResponse hello(ClienteLab07.Service.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.marketsoft.pucp.edu.pe/Servicio/helloRequest", ReplyAction="http://services.marketsoft.pucp.edu.pe/Servicio/helloResponse")]
        System.Threading.Tasks.Task<ClienteLab07.Service.helloResponse> helloAsync(ClienteLab07.Service.helloRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/")]
    public partial class promocion : itemVenta {
        
        private string nombreField;
        
        private lineaDetallePromocion[] lineasDetallePromocionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineasDetallePromocion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public lineaDetallePromocion[] lineasDetallePromocion {
            get {
                return this.lineasDetallePromocionField;
            }
            set {
                this.lineasDetallePromocionField = value;
                this.RaisePropertyChanged("lineasDetallePromocion");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/")]
    public partial class lineaDetallePromocion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private int idLineaDetallePromocionField;
        
        private productoPresentacion productoPresentacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idLineaDetallePromocion {
            get {
                return this.idLineaDetallePromocionField;
            }
            set {
                this.idLineaDetallePromocionField = value;
                this.RaisePropertyChanged("idLineaDetallePromocion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public productoPresentacion productoPresentacion {
            get {
                return this.productoPresentacionField;
            }
            set {
                this.productoPresentacionField = value;
                this.RaisePropertyChanged("productoPresentacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/")]
    public partial class productoPresentacion : itemVenta {
        
        private producto productoField;
        
        private presentacion presentacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public producto producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public presentacion presentacion {
            get {
                return this.presentacionField;
            }
            set {
                this.presentacionField = value;
                this.RaisePropertyChanged("presentacion");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/")]
    public partial class producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idProductoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                this.idProductoField = value;
                this.RaisePropertyChanged("idProducto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/")]
    public partial class presentacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idPresentacionField;
        
        private string unidadMedidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idPresentacion {
            get {
                return this.idPresentacionField;
            }
            set {
                this.idPresentacionField = value;
                this.RaisePropertyChanged("idPresentacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string unidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                this.unidadMedidaField = value;
                this.RaisePropertyChanged("unidadMedida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/")]
    public partial class tipoItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idTipoItemField;
        
        private string tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idTipoItem {
            get {
                return this.idTipoItemField;
            }
            set {
                this.idTipoItemField = value;
                this.RaisePropertyChanged("idTipoItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(productoPresentacion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(promocion))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/")]
    public partial class itemVenta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idItemVentaField;
        
        private tipoItem tipoItemField;
        
        private float precioUnitarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idItemVenta {
            get {
                return this.idItemVentaField;
            }
            set {
                this.idItemVentaField = value;
                this.RaisePropertyChanged("idItemVenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public tipoItem tipoItem {
            get {
                return this.tipoItemField;
            }
            set {
                this.tipoItemField = value;
                this.RaisePropertyChanged("tipoItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public float precioUnitario {
            get {
                return this.precioUnitarioField;
            }
            set {
                this.precioUnitarioField = value;
                this.RaisePropertyChanged("precioUnitario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPromociones", WrapperNamespace="http://services.marketsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPromocionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteLab07.Service.promocion Promocion;
        
        public insertarPromocionesRequest() {
        }
        
        public insertarPromocionesRequest(ClienteLab07.Service.promocion Promocion) {
            this.Promocion = Promocion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPromocionesResponse", WrapperNamespace="http://services.marketsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPromocionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPromocionesResponse() {
        }
        
        public insertarPromocionesResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarPromociones", WrapperNamespace="http://services.marketsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarPromocionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteLab07.Service.promocion Promocion;
        
        public actualizarPromocionesRequest() {
        }
        
        public actualizarPromocionesRequest(ClienteLab07.Service.promocion Promocion) {
            this.Promocion = Promocion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarPromocionesResponse", WrapperNamespace="http://services.marketsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarPromocionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarPromocionesResponse() {
        }
        
        public actualizarPromocionesResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPromociones", WrapperNamespace="http://services.marketsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPromocionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_promocion;
        
        public eliminarPromocionesRequest() {
        }
        
        public eliminarPromocionesRequest(int id_promocion) {
            this.id_promocion = id_promocion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPromocionesResponse", WrapperNamespace="http://services.marketsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPromocionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPromocionesResponse() {
        }
        
        public eliminarPromocionesResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPromociones", WrapperNamespace="http://services.marketsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPromocionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarPromocionesRequest() {
        }
        
        public listarPromocionesRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPromocionesResponse", WrapperNamespace="http://services.marketsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPromocionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteLab07.Service.promocion[] @return;
        
        public listarPromocionesResponse() {
        }
        
        public listarPromocionesResponse(ClienteLab07.Service.promocion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductos", WrapperNamespace="http://services.marketsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarProductosRequest() {
        }
        
        public listarProductosRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductosResponse", WrapperNamespace="http://services.marketsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteLab07.Service.productoPresentacion[] @return;
        
        public listarProductosResponse() {
        }
        
        public listarProductosResponse(ClienteLab07.Service.productoPresentacion[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://services.marketsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://services.marketsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.marketsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioChannel : ClienteLab07.Service.Servicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<ClienteLab07.Service.Servicio>, ClienteLab07.Service.Servicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteLab07.Service.insertarPromocionesResponse ClienteLab07.Service.Servicio.insertarPromociones(ClienteLab07.Service.insertarPromocionesRequest request) {
            return base.Channel.insertarPromociones(request);
        }
        
        public int insertarPromociones(ClienteLab07.Service.promocion Promocion) {
            ClienteLab07.Service.insertarPromocionesRequest inValue = new ClienteLab07.Service.insertarPromocionesRequest();
            inValue.Promocion = Promocion;
            ClienteLab07.Service.insertarPromocionesResponse retVal = ((ClienteLab07.Service.Servicio)(this)).insertarPromociones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteLab07.Service.insertarPromocionesResponse> ClienteLab07.Service.Servicio.insertarPromocionesAsync(ClienteLab07.Service.insertarPromocionesRequest request) {
            return base.Channel.insertarPromocionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteLab07.Service.insertarPromocionesResponse> insertarPromocionesAsync(ClienteLab07.Service.promocion Promocion) {
            ClienteLab07.Service.insertarPromocionesRequest inValue = new ClienteLab07.Service.insertarPromocionesRequest();
            inValue.Promocion = Promocion;
            return ((ClienteLab07.Service.Servicio)(this)).insertarPromocionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteLab07.Service.actualizarPromocionesResponse ClienteLab07.Service.Servicio.actualizarPromociones(ClienteLab07.Service.actualizarPromocionesRequest request) {
            return base.Channel.actualizarPromociones(request);
        }
        
        public int actualizarPromociones(ClienteLab07.Service.promocion Promocion) {
            ClienteLab07.Service.actualizarPromocionesRequest inValue = new ClienteLab07.Service.actualizarPromocionesRequest();
            inValue.Promocion = Promocion;
            ClienteLab07.Service.actualizarPromocionesResponse retVal = ((ClienteLab07.Service.Servicio)(this)).actualizarPromociones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteLab07.Service.actualizarPromocionesResponse> ClienteLab07.Service.Servicio.actualizarPromocionesAsync(ClienteLab07.Service.actualizarPromocionesRequest request) {
            return base.Channel.actualizarPromocionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteLab07.Service.actualizarPromocionesResponse> actualizarPromocionesAsync(ClienteLab07.Service.promocion Promocion) {
            ClienteLab07.Service.actualizarPromocionesRequest inValue = new ClienteLab07.Service.actualizarPromocionesRequest();
            inValue.Promocion = Promocion;
            return ((ClienteLab07.Service.Servicio)(this)).actualizarPromocionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteLab07.Service.eliminarPromocionesResponse ClienteLab07.Service.Servicio.eliminarPromociones(ClienteLab07.Service.eliminarPromocionesRequest request) {
            return base.Channel.eliminarPromociones(request);
        }
        
        public int eliminarPromociones(int id_promocion) {
            ClienteLab07.Service.eliminarPromocionesRequest inValue = new ClienteLab07.Service.eliminarPromocionesRequest();
            inValue.id_promocion = id_promocion;
            ClienteLab07.Service.eliminarPromocionesResponse retVal = ((ClienteLab07.Service.Servicio)(this)).eliminarPromociones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteLab07.Service.eliminarPromocionesResponse> ClienteLab07.Service.Servicio.eliminarPromocionesAsync(ClienteLab07.Service.eliminarPromocionesRequest request) {
            return base.Channel.eliminarPromocionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteLab07.Service.eliminarPromocionesResponse> eliminarPromocionesAsync(int id_promocion) {
            ClienteLab07.Service.eliminarPromocionesRequest inValue = new ClienteLab07.Service.eliminarPromocionesRequest();
            inValue.id_promocion = id_promocion;
            return ((ClienteLab07.Service.Servicio)(this)).eliminarPromocionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteLab07.Service.listarPromocionesResponse ClienteLab07.Service.Servicio.listarPromociones(ClienteLab07.Service.listarPromocionesRequest request) {
            return base.Channel.listarPromociones(request);
        }
        
        public ClienteLab07.Service.promocion[] listarPromociones(string nombre) {
            ClienteLab07.Service.listarPromocionesRequest inValue = new ClienteLab07.Service.listarPromocionesRequest();
            inValue.nombre = nombre;
            ClienteLab07.Service.listarPromocionesResponse retVal = ((ClienteLab07.Service.Servicio)(this)).listarPromociones(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteLab07.Service.listarPromocionesResponse> ClienteLab07.Service.Servicio.listarPromocionesAsync(ClienteLab07.Service.listarPromocionesRequest request) {
            return base.Channel.listarPromocionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteLab07.Service.listarPromocionesResponse> listarPromocionesAsync(string nombre) {
            ClienteLab07.Service.listarPromocionesRequest inValue = new ClienteLab07.Service.listarPromocionesRequest();
            inValue.nombre = nombre;
            return ((ClienteLab07.Service.Servicio)(this)).listarPromocionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteLab07.Service.listarProductosResponse ClienteLab07.Service.Servicio.listarProductos(ClienteLab07.Service.listarProductosRequest request) {
            return base.Channel.listarProductos(request);
        }
        
        public ClienteLab07.Service.productoPresentacion[] listarProductos(string nombre) {
            ClienteLab07.Service.listarProductosRequest inValue = new ClienteLab07.Service.listarProductosRequest();
            inValue.nombre = nombre;
            ClienteLab07.Service.listarProductosResponse retVal = ((ClienteLab07.Service.Servicio)(this)).listarProductos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteLab07.Service.listarProductosResponse> ClienteLab07.Service.Servicio.listarProductosAsync(ClienteLab07.Service.listarProductosRequest request) {
            return base.Channel.listarProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteLab07.Service.listarProductosResponse> listarProductosAsync(string nombre) {
            ClienteLab07.Service.listarProductosRequest inValue = new ClienteLab07.Service.listarProductosRequest();
            inValue.nombre = nombre;
            return ((ClienteLab07.Service.Servicio)(this)).listarProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteLab07.Service.helloResponse ClienteLab07.Service.Servicio.hello(ClienteLab07.Service.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            ClienteLab07.Service.helloRequest inValue = new ClienteLab07.Service.helloRequest();
            inValue.name = name;
            ClienteLab07.Service.helloResponse retVal = ((ClienteLab07.Service.Servicio)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteLab07.Service.helloResponse> ClienteLab07.Service.Servicio.helloAsync(ClienteLab07.Service.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteLab07.Service.helloResponse> helloAsync(string name) {
            ClienteLab07.Service.helloRequest inValue = new ClienteLab07.Service.helloRequest();
            inValue.name = name;
            return ((ClienteLab07.Service.Servicio)(this)).helloAsync(inValue);
        }
    }
}
