//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratorioNro09.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.musicsoft.pucp.edu.pe/", ConfigurationName="Service.Servicio")]
    public interface Servicio {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.musicsoft.pucp.edu.pe/Servicio/listarGenerosRequest", ReplyAction="http://services.musicsoft.pucp.edu.pe/Servicio/listarGenerosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LaboratorioNro09.Service.listarGenerosResponse listarGeneros(LaboratorioNro09.Service.listarGenerosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.musicsoft.pucp.edu.pe/Servicio/listarGenerosRequest", ReplyAction="http://services.musicsoft.pucp.edu.pe/Servicio/listarGenerosResponse")]
        System.Threading.Tasks.Task<LaboratorioNro09.Service.listarGenerosResponse> listarGenerosAsync(LaboratorioNro09.Service.listarGenerosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.musicsoft.pucp.edu.pe/Servicio/listarArtistasRequest", ReplyAction="http://services.musicsoft.pucp.edu.pe/Servicio/listarArtistasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LaboratorioNro09.Service.listarArtistasResponse listarArtistas(LaboratorioNro09.Service.listarArtistasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.musicsoft.pucp.edu.pe/Servicio/listarArtistasRequest", ReplyAction="http://services.musicsoft.pucp.edu.pe/Servicio/listarArtistasResponse")]
        System.Threading.Tasks.Task<LaboratorioNro09.Service.listarArtistasResponse> listarArtistasAsync(LaboratorioNro09.Service.listarArtistasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.musicsoft.pucp.edu.pe/Servicio/insertarAlbumRequest", ReplyAction="http://services.musicsoft.pucp.edu.pe/Servicio/insertarAlbumResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LaboratorioNro09.Service.insertarAlbumResponse insertarAlbum(LaboratorioNro09.Service.insertarAlbumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.musicsoft.pucp.edu.pe/Servicio/insertarAlbumRequest", ReplyAction="http://services.musicsoft.pucp.edu.pe/Servicio/insertarAlbumResponse")]
        System.Threading.Tasks.Task<LaboratorioNro09.Service.insertarAlbumResponse> insertarAlbumAsync(LaboratorioNro09.Service.insertarAlbumRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.musicsoft.pucp.edu.pe/Servicio/listarAlbumsRequest", ReplyAction="http://services.musicsoft.pucp.edu.pe/Servicio/listarAlbumsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LaboratorioNro09.Service.listarAlbumsResponse listarAlbums(LaboratorioNro09.Service.listarAlbumsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.musicsoft.pucp.edu.pe/Servicio/listarAlbumsRequest", ReplyAction="http://services.musicsoft.pucp.edu.pe/Servicio/listarAlbumsResponse")]
        System.Threading.Tasks.Task<LaboratorioNro09.Service.listarAlbumsResponse> listarAlbumsAsync(LaboratorioNro09.Service.listarAlbumsRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.musicsoft.pucp.edu.pe/Servicio/listarEmpresasRequest", ReplyAction="http://services.musicsoft.pucp.edu.pe/Servicio/listarEmpresasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LaboratorioNro09.Service.listarEmpresasResponse listarEmpresas(LaboratorioNro09.Service.listarEmpresasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.musicsoft.pucp.edu.pe/Servicio/listarEmpresasRequest", ReplyAction="http://services.musicsoft.pucp.edu.pe/Servicio/listarEmpresasResponse")]
        System.Threading.Tasks.Task<LaboratorioNro09.Service.listarEmpresasResponse> listarEmpresasAsync(LaboratorioNro09.Service.listarEmpresasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.musicsoft.pucp.edu.pe/")]
    public partial class generoMusical : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idGeneroField;
        
        private string nombreGeneroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idGenero {
            get {
                return this.idGeneroField;
            }
            set {
                this.idGeneroField = value;
                this.RaisePropertyChanged("idGenero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreGenero {
            get {
                return this.nombreGeneroField;
            }
            set {
                this.nombreGeneroField = value;
                this.RaisePropertyChanged("nombreGenero");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.musicsoft.pucp.edu.pe/")]
    public partial class track : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string duracionField;
        
        private int idTrackField;
        
        private string nombreTrackField;
        
        private int posicionAlbumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string duracion {
            get {
                return this.duracionField;
            }
            set {
                this.duracionField = value;
                this.RaisePropertyChanged("duracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idTrack {
            get {
                return this.idTrackField;
            }
            set {
                this.idTrackField = value;
                this.RaisePropertyChanged("idTrack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreTrack {
            get {
                return this.nombreTrackField;
            }
            set {
                this.nombreTrackField = value;
                this.RaisePropertyChanged("nombreTrack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int posicionAlbum {
            get {
                return this.posicionAlbumField;
            }
            set {
                this.posicionAlbumField = value;
                this.RaisePropertyChanged("posicionAlbum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.musicsoft.pucp.edu.pe/")]
    public partial class empresaDiscografica : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEmpresaField;
        
        private string nombreEmpresaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                this.idEmpresaField = value;
                this.RaisePropertyChanged("idEmpresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombreEmpresa {
            get {
                return this.nombreEmpresaField;
            }
            set {
                this.nombreEmpresaField = value;
                this.RaisePropertyChanged("nombreEmpresa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.musicsoft.pucp.edu.pe/")]
    public partial class albumMusical : object, System.ComponentModel.INotifyPropertyChanged {
        
        private artista artistaField;
        
        private string descripcionField;
        
        private empresaDiscografica empresaDiscograficaField;
        
        private System.DateTime fechaLanzamientoField;
        
        private bool fechaLanzamientoFieldSpecified;
        
        private generoMusical generoMusicalField;
        
        private int idAlbumField;
        
        private string nombreAlbumField;
        
        private byte[] portadaField;
        
        private track[] tracksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public artista artista {
            get {
                return this.artistaField;
            }
            set {
                this.artistaField = value;
                this.RaisePropertyChanged("artista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public empresaDiscografica empresaDiscografica {
            get {
                return this.empresaDiscograficaField;
            }
            set {
                this.empresaDiscograficaField = value;
                this.RaisePropertyChanged("empresaDiscografica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaLanzamiento {
            get {
                return this.fechaLanzamientoField;
            }
            set {
                this.fechaLanzamientoField = value;
                this.RaisePropertyChanged("fechaLanzamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaLanzamientoSpecified {
            get {
                return this.fechaLanzamientoFieldSpecified;
            }
            set {
                this.fechaLanzamientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaLanzamientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public generoMusical generoMusical {
            get {
                return this.generoMusicalField;
            }
            set {
                this.generoMusicalField = value;
                this.RaisePropertyChanged("generoMusical");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idAlbum {
            get {
                return this.idAlbumField;
            }
            set {
                this.idAlbumField = value;
                this.RaisePropertyChanged("idAlbum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombreAlbum {
            get {
                return this.nombreAlbumField;
            }
            set {
                this.nombreAlbumField = value;
                this.RaisePropertyChanged("nombreAlbum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] portada {
            get {
                return this.portadaField;
            }
            set {
                this.portadaField = value;
                this.RaisePropertyChanged("portada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tracks", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public track[] tracks {
            get {
                return this.tracksField;
            }
            set {
                this.tracksField = value;
                this.RaisePropertyChanged("tracks");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.musicsoft.pucp.edu.pe/")]
    public partial class artista : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idArtistaField;
        
        private string nacionalidadField;
        
        private string nombreArtistaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idArtista {
            get {
                return this.idArtistaField;
            }
            set {
                this.idArtistaField = value;
                this.RaisePropertyChanged("idArtista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("nacionalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreArtista {
            get {
                return this.nombreArtistaField;
            }
            set {
                this.nombreArtistaField = value;
                this.RaisePropertyChanged("nombreArtista");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarGeneros", WrapperNamespace="http://services.musicsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarGenerosRequest {
        
        public listarGenerosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarGenerosResponse", WrapperNamespace="http://services.musicsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarGenerosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.musicsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LaboratorioNro09.Service.generoMusical[] @return;
        
        public listarGenerosResponse() {
        }
        
        public listarGenerosResponse(LaboratorioNro09.Service.generoMusical[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarArtistas", WrapperNamespace="http://services.musicsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarArtistasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.musicsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarArtistasRequest() {
        }
        
        public listarArtistasRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarArtistasResponse", WrapperNamespace="http://services.musicsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarArtistasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.musicsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LaboratorioNro09.Service.artista[] @return;
        
        public listarArtistasResponse() {
        }
        
        public listarArtistasResponse(LaboratorioNro09.Service.artista[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAlbum", WrapperNamespace="http://services.musicsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarAlbumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.musicsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LaboratorioNro09.Service.albumMusical album;
        
        public insertarAlbumRequest() {
        }
        
        public insertarAlbumRequest(LaboratorioNro09.Service.albumMusical album) {
            this.album = album;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarAlbumResponse", WrapperNamespace="http://services.musicsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarAlbumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.musicsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarAlbumResponse() {
        }
        
        public insertarAlbumResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlbums", WrapperNamespace="http://services.musicsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAlbumsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.musicsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarAlbumsRequest() {
        }
        
        public listarAlbumsRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAlbumsResponse", WrapperNamespace="http://services.musicsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAlbumsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.musicsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LaboratorioNro09.Service.albumMusical[] @return;
        
        public listarAlbumsResponse() {
        }
        
        public listarAlbumsResponse(LaboratorioNro09.Service.albumMusical[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresas", WrapperNamespace="http://services.musicsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpresasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.musicsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarEmpresasRequest() {
        }
        
        public listarEmpresasRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEmpresasResponse", WrapperNamespace="http://services.musicsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEmpresasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.musicsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LaboratorioNro09.Service.empresaDiscografica[] @return;
        
        public listarEmpresasResponse() {
        }
        
        public listarEmpresasResponse(LaboratorioNro09.Service.empresaDiscografica[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioChannel : LaboratorioNro09.Service.Servicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<LaboratorioNro09.Service.Servicio>, LaboratorioNro09.Service.Servicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LaboratorioNro09.Service.listarGenerosResponse LaboratorioNro09.Service.Servicio.listarGeneros(LaboratorioNro09.Service.listarGenerosRequest request) {
            return base.Channel.listarGeneros(request);
        }
        
        public LaboratorioNro09.Service.generoMusical[] listarGeneros() {
            LaboratorioNro09.Service.listarGenerosRequest inValue = new LaboratorioNro09.Service.listarGenerosRequest();
            LaboratorioNro09.Service.listarGenerosResponse retVal = ((LaboratorioNro09.Service.Servicio)(this)).listarGeneros(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LaboratorioNro09.Service.listarGenerosResponse> LaboratorioNro09.Service.Servicio.listarGenerosAsync(LaboratorioNro09.Service.listarGenerosRequest request) {
            return base.Channel.listarGenerosAsync(request);
        }
        
        public System.Threading.Tasks.Task<LaboratorioNro09.Service.listarGenerosResponse> listarGenerosAsync() {
            LaboratorioNro09.Service.listarGenerosRequest inValue = new LaboratorioNro09.Service.listarGenerosRequest();
            return ((LaboratorioNro09.Service.Servicio)(this)).listarGenerosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LaboratorioNro09.Service.listarArtistasResponse LaboratorioNro09.Service.Servicio.listarArtistas(LaboratorioNro09.Service.listarArtistasRequest request) {
            return base.Channel.listarArtistas(request);
        }
        
        public LaboratorioNro09.Service.artista[] listarArtistas(string nombre) {
            LaboratorioNro09.Service.listarArtistasRequest inValue = new LaboratorioNro09.Service.listarArtistasRequest();
            inValue.nombre = nombre;
            LaboratorioNro09.Service.listarArtistasResponse retVal = ((LaboratorioNro09.Service.Servicio)(this)).listarArtistas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LaboratorioNro09.Service.listarArtistasResponse> LaboratorioNro09.Service.Servicio.listarArtistasAsync(LaboratorioNro09.Service.listarArtistasRequest request) {
            return base.Channel.listarArtistasAsync(request);
        }
        
        public System.Threading.Tasks.Task<LaboratorioNro09.Service.listarArtistasResponse> listarArtistasAsync(string nombre) {
            LaboratorioNro09.Service.listarArtistasRequest inValue = new LaboratorioNro09.Service.listarArtistasRequest();
            inValue.nombre = nombre;
            return ((LaboratorioNro09.Service.Servicio)(this)).listarArtistasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LaboratorioNro09.Service.insertarAlbumResponse LaboratorioNro09.Service.Servicio.insertarAlbum(LaboratorioNro09.Service.insertarAlbumRequest request) {
            return base.Channel.insertarAlbum(request);
        }
        
        public int insertarAlbum(LaboratorioNro09.Service.albumMusical album) {
            LaboratorioNro09.Service.insertarAlbumRequest inValue = new LaboratorioNro09.Service.insertarAlbumRequest();
            inValue.album = album;
            LaboratorioNro09.Service.insertarAlbumResponse retVal = ((LaboratorioNro09.Service.Servicio)(this)).insertarAlbum(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LaboratorioNro09.Service.insertarAlbumResponse> LaboratorioNro09.Service.Servicio.insertarAlbumAsync(LaboratorioNro09.Service.insertarAlbumRequest request) {
            return base.Channel.insertarAlbumAsync(request);
        }
        
        public System.Threading.Tasks.Task<LaboratorioNro09.Service.insertarAlbumResponse> insertarAlbumAsync(LaboratorioNro09.Service.albumMusical album) {
            LaboratorioNro09.Service.insertarAlbumRequest inValue = new LaboratorioNro09.Service.insertarAlbumRequest();
            inValue.album = album;
            return ((LaboratorioNro09.Service.Servicio)(this)).insertarAlbumAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LaboratorioNro09.Service.listarAlbumsResponse LaboratorioNro09.Service.Servicio.listarAlbums(LaboratorioNro09.Service.listarAlbumsRequest request) {
            return base.Channel.listarAlbums(request);
        }
        
        public LaboratorioNro09.Service.albumMusical[] listarAlbums(string nombre) {
            LaboratorioNro09.Service.listarAlbumsRequest inValue = new LaboratorioNro09.Service.listarAlbumsRequest();
            inValue.nombre = nombre;
            LaboratorioNro09.Service.listarAlbumsResponse retVal = ((LaboratorioNro09.Service.Servicio)(this)).listarAlbums(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LaboratorioNro09.Service.listarAlbumsResponse> LaboratorioNro09.Service.Servicio.listarAlbumsAsync(LaboratorioNro09.Service.listarAlbumsRequest request) {
            return base.Channel.listarAlbumsAsync(request);
        }
        
        public System.Threading.Tasks.Task<LaboratorioNro09.Service.listarAlbumsResponse> listarAlbumsAsync(string nombre) {
            LaboratorioNro09.Service.listarAlbumsRequest inValue = new LaboratorioNro09.Service.listarAlbumsRequest();
            inValue.nombre = nombre;
            return ((LaboratorioNro09.Service.Servicio)(this)).listarAlbumsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LaboratorioNro09.Service.listarEmpresasResponse LaboratorioNro09.Service.Servicio.listarEmpresas(LaboratorioNro09.Service.listarEmpresasRequest request) {
            return base.Channel.listarEmpresas(request);
        }
        
        public LaboratorioNro09.Service.empresaDiscografica[] listarEmpresas(string nombre) {
            LaboratorioNro09.Service.listarEmpresasRequest inValue = new LaboratorioNro09.Service.listarEmpresasRequest();
            inValue.nombre = nombre;
            LaboratorioNro09.Service.listarEmpresasResponse retVal = ((LaboratorioNro09.Service.Servicio)(this)).listarEmpresas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LaboratorioNro09.Service.listarEmpresasResponse> LaboratorioNro09.Service.Servicio.listarEmpresasAsync(LaboratorioNro09.Service.listarEmpresasRequest request) {
            return base.Channel.listarEmpresasAsync(request);
        }
        
        public System.Threading.Tasks.Task<LaboratorioNro09.Service.listarEmpresasResponse> listarEmpresasAsync(string nombre) {
            LaboratorioNro09.Service.listarEmpresasRequest inValue = new LaboratorioNro09.Service.listarEmpresasRequest();
            inValue.nombre = nombre;
            return ((LaboratorioNro09.Service.Servicio)(this)).listarEmpresasAsync(inValue);
        }
    }
}
